### ISSUE TITLE
Porting to Vault Transit Engine

### ISSUE THREAD

**Issue by martinssipenko** [LeSuisse/vault-gpg-plugin#8]
Hi,

Just curious if you have any plans to port this to be an official Vault Secret Engine?

**Comment by LeSuisse** [comment]
Hi,

Thanks for your interest!

Yes, I intend to propose a PR to hashicorp/vault and support this secret engine over there. I want to do it for quite some time now but let's just say I'm lazy. Anyway, I expect to get this done in the next few weeks.

I just want to verify/add some missing things before:
 * have a way to generate a revocation certificate
 * handle properly keys that are imported into the secret engine but does not have all the capacities (e.g. what does happen when you import a key than can not sign and call the /gpg/sign route with it)
 * have a plan to manage subkeys since it seems to be a recurrent demand in the Vault issues. I want to be sure the API can support them cleanly to not introduce a breaking change in the future.

**Comment by LeSuisse** [comment]
Hi,

FYI, I just opened a PR to merge this plugin into Vault: https://github.com/hashicorp/vault/pull/4308

Revocation certificate has not been handled has the underlying OpenPGP Golang library does not support it out of the box and I would need to duplicate some code of the library to make it possible.
