### ISSUE TITLE
Signing rpm's with the generated signatures

### ISSUE THREAD

**Issue by SigmaDee** [LeSuisse/vault-gpg-plugin#89]
This may be obvious, but I have configured the plugin and been able to generate signatures, but I don't understand how to actually "attach" those signatures to the rpm's I want to sign. Is there a way to configure rpmsign to use the vault server as the source of the signature?

Thanks!

**Comment by LeSuisse** [comment]
Hi,

It's not that obvious, the last time I checked there was two solutions:
 * do the manipulations yourself to include the signatures
 * let `rpm` do it for you by tricking it into thinking it interacts with the `gpg` CLI
 
 I'm currently using the second one for the [@TuleapOpenALM](https://github.com/Enalean/tuleap/) project, mostly because it seemed the solution that required the less work and once I got it running it was good enough ¯\_(ツ)_/¯
 
 I wrote about it here: https://blog.tuleap.org/delivering-rpm-packages-securely-and-continuously-jenkins-and-hashicorp-vault/
 
The gist of it is that you can tell to `rpm` which `gpg` CLI to use with `__gpg_sign_cmd` and use a shell script to wrap the call to Vault:

https://tuleap.net/plugins/git/tuleap/tools/sign-packages-repositories?a=blob&hb=89eb7907a18e31b758f2c3371bd05d7ec9c8002b&h=f72c2161bafd49897bb558ab2faaf656e3218d2e&f=sign-packages.sh#L24
https://tuleap.net/plugins/git/tuleap/tools/sign-packages-repositories?a=blob&hb=89eb7907a18e31b758f2c3371bd05d7ec9c8002b&h=75c585193fa6a5c6c8be58f73b58375c1e50abad&f=gpg-lookalike-vault-rpm.sh

**Comment by SigmaDee** [comment]
Thank you very much. After some fiddling around I got that to work like a charm.

Just a note. The article at the link you provided above concludes with "Being able to sign data with a GPG key directly in Vault would be a major improvement as it would greatly reduce the exposure of the key."
So if you intended to write the full story there, I think you may have forgotten to.
